mod commands;
mod diagnostics;
mod locales;
mod models;
mod operations;
mod p4;
mod settings;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .manage(operations::OperationRegistry::default())
        .manage(commands::WorkspaceRootRegistry::default())
        .invoke_handler(tauri::generate_handler![
            commands::detect_p4,
            commands::test_connection,
            commands::open_workspace,
            commands::login,
            commands::login_status,
            commands::logout,
            commands::list_trust,
            commands::load_settings,
            commands::save_language,
            commands::save_revert_preference,
            commands::load_locales,
            commands::remember_connection,
            commands::toggle_favorite_connection,
            commands::list_workspaces,
            commands::inspect_workspace,
            commands::update_workspace,
            commands::create_workspace,
            commands::delete_workspace,
            commands::rename_workspace,
            commands::list_streams,
            commands::switch_stream,
            commands::list_depots,
            commands::list_depot_directories,
            commands::list_depot_files,
            commands::list_pending_changes,
            commands::list_jobs,
            commands::list_labels,
            commands::list_fixes,
            commands::fix_job,
            commands::unfix_job,
            commands::list_submitted_changes,
            commands::describe_change,
            commands::preview_undo,
            commands::undo_change,
            commands::list_shelved_changes,
            commands::list_opened_files,
            commands::list_workspace_files,
            commands::list_local_workspace_directory,
            commands::ignore_local_file,
            commands::delete_local_file,
            commands::preview_sync,
            commands::repair_sync_have_list,
            commands::start_sync,
            commands::start_submit,
            commands::cancel_operation,
            commands::edit_files,
            commands::add_files,
            commands::delete_files,
            commands::lock_files,
            commands::unlock_files,
            commands::resolve_files,
            commands::preview_resolve,
            commands::move_file,
            commands::reconcile_files,
            commands::preview_reconcile,
            commands::list_shelved_files,
            commands::reopen_files,
            commands::diff_file,
            commands::file_history,
            commands::print_revision,
            commands::save_revision,
            commands::save_change_files,
            commands::save_shelved_file,
            commands::diff_revisions,
            commands::diff_revision_workspace,
            commands::annotate_file,
            commands::diff_shelved_file,
            commands::submit_change,
            commands::submit_preflight,
            commands::shelve_file,
            commands::preview_unshelve,
            commands::unshelve_files,
            commands::reshelve_files,
            commands::delete_shelf_files,
            commands::revert_files,
            commands::preview_revert_unchanged,
            commands::preview_revert_all,
            commands::preview_revert_selected,
            commands::revert_unchanged,
            commands::edit_change,
            commands::delete_change,
            commands::create_change,
            commands::list_cli_log,
            commands::clear_cli_log,
            commands::ui_snapshot_enabled,
            commands::write_ui_snapshot,
            commands::read_ui_agent_command,
            commands::write_ui_agent_response,
            commands::reveal_path
        ])
        .run(tauri::generate_context!())
        .expect("failed to run P4FNV");
}
